spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/user-access-management}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:devtran}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret-key: 124GHnOgUWPMfB7ykdugUFj9zxUdQSyhppxB9t2seAMW+ylqgVtitHoZ3BBrVGGq/LHKdNyWJ2FMOePliKsiQg==
  valid-duration: 3600
  refreshable-duration: 36000